version: '3.8'

services:

  # Your New FastAPI Service
  web:
    build: .
    image: german-word-game:latest
    container_name: fastapi-game-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine  # Lightweight production-ready Redis image
    container_name: redis-game-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  

volumes:
  redis_data: